name: Docker Build for Dev

on:
  push:
    branches: ["main"]

jobs:
  docker-dev-build:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name:  Build Docker image
        run: docker build -t vite-dev-app -f Dockerfile .

      - name:  Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name:  Build & Push Docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vite-dev-app:latest
